
const items = {

  chinese_tea: {
    puerh: {
      black: [
        {
          name: "Red Dayi Menghai black pu-erh",
          id: '1',
          imgSrc: "https://i.postimg.cc/0NLGt35m/1.webp",
          // imgSrc: 'https://i.postimg.cc/W3xxZ3Rz/1-ah-Gx-QEFG3-transformed.png',
          priceFor100: 15,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Yiwu Big Tree Fuhai black pu-erh",
          id: '2',
          imgSrc: "https://i.postimg.cc/cLkB3CVF/2.webp",
          priceFor100: 10,
          fullWeight: 300,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Xiaguan Tuo Cha black pu-erh",
          id: '3',
          imgSrc: "https://i.postimg.cc/2jnGtzZ5/3.webp",
          priceFor100: 7.25,
          fullWeight: 150,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Tuo Cha Taocha Xiaguan black pu-erh",
          id: '4',
          imgSrc: "https://i.postimg.cc/zX57Z9CF/4.webp",
          priceFor100: 6,
          fullWeight: 170,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Year 2000 Gu Shu Loose Leaf black Pu-Erh",
          id: '5',
          imgSrc: "https://i.postimg.cc/MGcbmxwq/5.webp",
          priceFor100: 10,
          fullWeight: 500,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Mini Tuo Cha 2005 black pu-erh",
          id: '6',
          imgSrc: "https://i.postimg.cc/sDccVwKd/6.webp",
          priceFor100: 10,
          fullWeight: 150,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Early Spring 2011 eco black pu-erh",
          id: '7',
          imgSrc: "https://i.postimg.cc/Cxx4dk6Z/7.webp",
          priceFor100: 10,
          fullWeight: 230,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Jin Gwa Big Leaf Loose Leaf black pu-erh",
          id: '8',
          imgSrc: "https://i.postimg.cc/GtPjTQCD/8.webp",
          priceFor100: 10,
          fullWeight: 500,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
        {
          name: "Emperor's 2010 black pu-erh",
          id: '9',
          imgSrc: "https://i.postimg.cc/nrfkLW6Z/9.webp",
          priceFor100: 10,
          fullWeight: 330,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'black',
        },
      ],
      green: [
        {
          name: "2007 Nan Qiao green pu-erh",
          id: '1121',
          imgSrc: 'https://i.postimg.cc/d3YhmpfY/1121.jpg',
          priceFor100: 7.5,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'green',
        },
        {
          name: "2021 Lao Tong Zhi Old Comrade green pu-erh",
          id: '1122',
          imgSrc: 'https://i.postimg.cc/hv1fCMF7/1122.jpg',
          priceFor100: 5,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'green',
        },
        {
          name: "2020 Spring Xiao Hu Sai green pu-erh",
          id: '1123',
          imgSrc: 'https://i.postimg.cc/m2TccxM3/1123.jpg',
          priceFor100: 10,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'green',
        },
        {
          name: "2015 Haiwan Liang Xian Pin green pu-erh",
          id: '1124',
          imgSrc: 'https://i.postimg.cc/3rX4JryJ/1124.jpg',
          priceFor100: 45,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'pu-erh',
          subsubcategory: 'green',
        },
      ]
    },
    oolong: {
      tie_guan_yin: [
        {
          name: "SELECTED GRADE 2023 SPRING HARVEST tie guan yin",
          id: '1211',
          imgSrc: 'https://i.postimg.cc/xdQjZMRv/1211.webp',
          priceFor100: 20,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'oolong',
          subsubcategory: 'tie_guan_yin',
        },
        {
          name: "Iron Buddha Mellow tie guan yin",
          id: '1212',
          imgSrc: 'https://i.postimg.cc/FKxFXzW2/1212.webp',
          priceFor100: 35,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'oolong',
          subsubcategory: 'tie_guan_yin',
        },
        {
          name: "Iron Buddha Monkey Pick tie guan yin",
          id: '1213',
          imgSrc: 'https://i.postimg.cc/tTCqqb87/1213.webp',
          priceFor100: 30,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'oolong',
          subsubcategory: 'tie_guan_yin',
        },
        {
          name: "spring 2023 fujian tie guan yin",
          id: '1214',
          imgSrc: 'https://i.postimg.cc/nrXnmkFJ/1214.webp',
          priceFor100: 7,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'oolong',
          subsubcategory: 'tie_guan_yin',
        },
      ],
      da_hong_pao: [
        {
          name: "spring 2021 da hong pao",
          id: '1221',
          imgSrc: 'https://i.postimg.cc/3JrctRmk/1221.webp',
          priceFor100: 15,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'oolong',
          subsubcategory: 'da_hong_pao',
        },
        {
          name: "spring 2023 da hong pao",
          id: '1222',
          imgSrc: 'https://i.postimg.cc/28HXMD72/1222.jpg',
          priceFor100: 10,
          fullWeight: 357,
          category: 'chinese_tea',
          subcategory: 'oolong',
          subsubcategory: 'da_hong_pao',
        },
      ]
    }
  },

  herbal_tea: {
    chamomile: [
      {
        name: "slavonia organic chamomile flowers",
        id: '211',
        imgSrc: 'https://i.postimg.cc/Gh2HdFvd/211.webp',
        priceFor100: 4,
        fullWeight: 357,
        category: 'herbal_tea',
        subcategory: 'chamomile',
      },
    ],
    peppermint: [
      {
        name: "bavaria peppermint tea leaf",
        id: '221',
        imgSrc: 'https://i.postimg.cc/QthdP1XL/221.webp',
        priceFor100: 6,
        fullWeight: 357,
        category: 'herbal_tea',
        subcategory: 'peppermint',
      },
      {
        name: "montenegro peppermint tea leaf",
        id: '222',
        imgSrc: 'https://i.postimg.cc/bJgwjrJZ/222.jpg',
        priceFor100: 5,
        fullWeight: 357,
        category: 'herbal_tea',
        subcategory: 'peppermint',
      },
    ],
    ivan_chai: [
      {
        name: "organic siberian ivan chai",
        id: '231',
        imgSrc: 'https://i.postimg.cc/fykDnvpP/231.webp',
        priceFor100: 1000,
        fullWeight: 357,
        category: 'herbal_tea',
        subcategory: 'ivan_chai',
      },
    ]
  },

  coffee: {
    brazil: [
      {
        name: "BRAZILIAN Dark Roast Coffee Beans",
        id: '311',
        imgSrc: 'https://i.postimg.cc/CMNpJ9Bx/311.webp',
        priceFor100: 7,
        fullWeight: 357,
        category: 'coffee',
        subcategory: 'brazil',
      },
    ],
    colombia: [
      {
        name: "COLOMBIA Inga Aponte Coffee Beans",
        id: '321',
        imgSrc: 'https://i.postimg.cc/brYMKNDN/321.webp',
        priceFor100: 9,
        fullWeight: 357,
        category: 'coffee',
        subcategory: 'colombia',
      },
    ]
  },

  teaware: {
    teapots: {
      clay: [
        {
          name: "Dragon Yixing Dark green clay Teapot",
          id: '4111',
          imgSrc: 'https://i.postimg.cc/brvnbQnH/4111.jpg',
          priceFor100: 350,
          category: 'teaware',
          subcategory: 'teapots',
          subsubcategory: 'clay',
        },
        {
          name: "Xi Shi Yixing Teapot",
          id: '4112',
          imgSrc: 'https://i.postimg.cc/FznLx7gt/4112.webp',
          priceFor100: 70,
          category: 'teaware',
          subcategory: 'teapots',
          subsubcategory: 'clay',
        },
        {
          name: "peony flower purple clay teapot",
          id: '4113',
          imgSrc: 'https://i.postimg.cc/XJLFp2rY/4113.jpg',
          priceFor100: 410,
          category: 'teaware',
          subcategory: 'teapots',
          subsubcategory: 'clay',
        },
      ],

      porcelain: [
        {
          name: "Chinese Sea Wave Porcelain Teapot",
          id: '4121',
          imgSrc: 'https://i.postimg.cc/PxWp0SWM/4121.webp',
          priceFor100: 50,
          category: 'teaware',
          subcategory: 'teapots',
          subsubcategory: 'porcelain',
        },
        {
          name: "Jingdezhen Porcelain Chinese Dragon Teapot",
          id: '4122',
          imgSrc: 'https://i.postimg.cc/7hqG4SXr/4122.webp',
          priceFor100: 37,
          category: 'teaware',
          subcategory: 'teapots',
          subsubcategory: 'porcelain',
        },
        {
          name: "Blue porcelain Teapot With Golden Flowers",
          id: '4123',
          imgSrc: 'https://i.postimg.cc/KzS396Mz/4123.webp',
          priceFor100: 40,
          category: 'teaware',
          subcategory: 'teapots',
          subsubcategory: 'porcelain',
        },
        {
          name: "Handmade Jianzhan Teapot With Sterling Silver Lotus",
          id: '4124',
          imgSrc: 'https://i.postimg.cc/JhBB5rtv/4124.webp',
          priceFor100: 105,
          category: 'teaware',
          subcategory: 'teapots',
          subsubcategory: 'porcelain',
        },

      ]
    },
    teacups: [
      {
        name: "Chinese Blue And White Porcelain Bat Tea Cup",
        id: '421',
        imgSrc: 'https://i.postimg.cc/3wX4yLkD/421.webp',
        priceFor100: 27,
        category: 'teaware',
        subcategory: 'teacups',
      },
      {
        name: "Shinoyaki Gold Gongfu Tea Cup",
        id: '422',
        imgSrc: 'https://i.postimg.cc/sxXvNswp/422.webp',
        priceFor100: 58,
        category: 'teaware',
        subcategory: 'teacups',
      },
      {
        name: "Vintage Japanese Mug with Wooden Handle",
        id: '423',
        imgSrc: 'https://i.postimg.cc/26T1GVFk/423.webp',
        priceFor100: 22,
        category: 'teaware',
        subcategory: 'teacups',
      },
      {
        name: "Jian Heavenly Flower Tea Cup ",
        id: '424',
        imgSrc: 'https://i.postimg.cc/bJqG1QnV/424.jpg',
        priceFor100: 12,
        category: 'teaware',
        subcategory: 'teacups',
      },
      {
        name: "Hand-Painted Porcelain Lotus Pond Tea Cup",
        id: '425',
        imgSrc: 'https://i.postimg.cc/3NcdMVcz/425.jpg',
        priceFor100: 17,
        category: 'teaware',
        subcategory: 'teacups',
      },
      {
        name: "Yixing Purple Clay Carved Dragon Tea Cup",
        id: '426',
        imgSrc: 'https://i.postimg.cc/bvcSwXwh/426.webp',
        priceFor100: 75,
        category: 'teaware',
        subcategory: 'teacups',
      },
    ],
    // gaiwans:[

    // ]
  }


}

module.exports = {
  items,
};
